### PR TITLE
Fix import bugs in text-transformers.py

### LINKED ISSUE #97: Find import bugs in "lightnin_examples/text-transformers.py"
## 🐛 Bug

I cannot import pytorch-lightning in colab. 
The file name that has error is `text-transformer.ipynb` (can be found in [jupyter link](https://github.com/PyTorchLightning/lightning-tutorials/blob/a2fb6468112b7e1dad501c3b6a17533a4adfeabc/.notebooks/lightning_examples/text-transformers.ipynb), [colab link](https://colab.research.google.com/github/PytorchLightning/lightning-tutorials/blob/publication/.notebooks/lightning_examples/text-transformers.ipynb))

### To Reproduce

1. Open `text-transformer.ipynb` in colab ([colab link](https://colab.research.google.com/github/PytorchLightning/lightning-tutorials/blob/publication/.notebooks/lightning_examples/text-transformers.ipynb))
2. Execute first and second code block
3. If you execute second code block, it will show you import error.

image

### Expected behavior

If I import pytorch-lightning, it should be imported without error.

### Solution

I tried to solve this problem myself and I somehow find that error is occurred, because torchtext version is lower than expected.
So If you add `torchtext>=0.9` in import statement, error can be fixed. 
```python
! pip install --quiet "datasets" "scipy" "torchmetrics>=0.3" "transformers" "scikit-learn" "torch>=1.6, <1.9" "torchtext>=0.9" "pytorch_lightning>=1.3"
```

If you find my solution is good, let me know I will make a PR.

### PR DESCRIPTION
**Pull request by hankyul2**
# Add torchtext version in .meta.yaml

closes #97

## Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you make sure to update the docs?
- [x] Did you write any new necessary tests?

## What does this PR do?

Fixes #97. 
In short, I try to fix import bugs in text-transformers.py by add `torchtext>=0.9` as requirements.

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Of course, I do! 😁

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
@hankyul2 mind fixing the failing cells, I have tried, but you have lock PR so maintainers can't edit it...

**Comment by hankyul2** [comment]
@Borda Ok. I will try to fix it.

**Comment by hankyul2** [comment]
@Borda 
I am so sorry, but what does failing cells mean?

**Comment by Borda** [comment]
> I am so sorry, but what do failing cells mean?

you can see the full test here: https://dev.azure.com/PytorchLightning/Tutorials/_build/results?buildId=44840&view=logs&j=86bb8c30-297f-58f2-418d-1ad5be677653&t=16cfed9e-a41b-5b0e-892e-bf130fd21fce

the particular error is:
```
    738             self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    739         )

~/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    680         """
    681         try:
--> 682             return trainer_fn(*args, **kwargs)
    683         # TODO: treat KeyboardInterrupt as BaseException (delete the code below) in v1.7
    684         except KeyboardInterrupt as exception:

~/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    770         # TODO: ckpt_path only in v1.7
    771         ckpt_path = ckpt_path or self.resume_from_checkpoint
--> 772         self._run(model, ckpt_path=ckpt_path)
    773 
    774         assert self.state.stopped

~/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model, ckpt_path)
   1132         self.call_hook("on_before_accelerator_backend_setup")
   1133         self.accelerator.setup_environment()
-> 1134         self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
   1135 
   1136         # check if we should delay restoring checkpoint till later

~/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _call_setup_hook(self)
   1432         if self.datamodule is not None:
   1433             self.datamodule.setup(stage=fn)
-> 1434         self.call_hook("setup", stage=fn)
   1435 
   1436         self.training_type_plugin.barrier("post_setup")

~/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in call_hook(self, hook_name, pl_module, *args, **kwargs)
   1494             model_fx = getattr(pl_module, hook_name, None)
   1495             if callable(model_fx):
-> 1496                 output = model_fx(*args, **kwargs)
   1497 
   1498             # *Bad code alert*

/tmp/ipykernel_421/309689209.py in setup(self, stage)
     71             return
     72         # Get dataloader by calling it - train_dataloader() is called after setup() by default
---> 73         train_loader = self.train_dataloader()
     74 
     75         # Calculate total steps

~/.local/lib/python3.9/site-packages/pytorch_lightning/core/hooks.py in train_dataloader(self)
    475                 return {'mnist': mnist_loader, 'cifar': cifar_loader}
    476         """
--> 477         raise NotImplementedError("`train_dataloader` must be implemented to be used with the Lightning Trainer")
    478 
    479     def test_dataloader(self) -> EVAL_DATALOADERS:

NotImplementedError: `train_dataloader` must be implemented to be used with the Lightning Trainer

=============================== warnings summary ===============================
../../../usr/local/lib/python3.9/dist-packages/_pytest/config/__init__.py:1183
  /usr/local/lib/python3.9/dist-packages/_pytest/config/__init__.py:1183: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    self.issue_config_time_warning(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED lightning_examples/text-transformers/text-transformers.ipynb::Cell 5
FAILED lightning_examples/text-transformers/text-transformers.ipynb::Cell 6
```

**Comment by hankyul2** [comment]
@Borda I changed code and the failing cells seem to be fixed now.

**Comment by Borda** [comment]
> I changed code and the failing cells seem to be fixed now.

cool, could you please also update the update date in meta file to be today and reset nb build :]

**Comment by hankyul2** [comment]
@Borda 
Thank you for your detailed instruction:)
I changed the updated date and build number.
Can you give me a hint about how to fix [this check error](https://github.com/PyTorchLightning/lightning-tutorials/runs/4393726604?check_suite_focus=true)

**Comment by Borda** [comment]
> Can you give me a hint about how to fix [this check error](https://github.com/PyTorchLightning/lightning-tutorials/runs/4393726604?check_suite_focus=true)

it says `Cell 5: Timeout of 300 seconds exceeded while executing cell. Failed to interrupt kernel in 5 seconds, so failing without traceback.`
so the cell takes too long and I see it does create DM and fit, so you can split it into two cels and also decrease nb of training epochs

**Comment by hankyul2** [comment]
@Borda 
The check error that I mentioned before seems to be fixed now. (I don't know why) Do you think that we should do more commits for this?

image

**Pull request merged**
