### PR TITLE
add video links for uva deep learning course

### PR DESCRIPTION
**Pull request by awaelchli**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?

Add links to the youtube videos for the UA tutorials

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
@awaelchli is it ready? :]

**Comment by awaelchli** [comment]
almost, just making sure I got all of them and that rendering of the  badge works

**Comment by phlippe** [comment]
Do we want the videos as badges as currently in this pull request, or iframes? @tchaton suggested frames, and I have them ready here: https://github.com/phlippe/lightning-tutorials/tree/youtube_videos (sorry, did it at the exact same time as this pull request came up). On our course website, we used the badges.

**Comment by awaelchli** [comment]
Hey @phlippe I think iframes are better and your branch could be converted to a PR. Let's go with yours :)

**Pull request closed without merging**
