### PR TITLE
add template example

### PR DESCRIPTION
**Pull request by edgarriba**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you make sure to update the docs?
- [x] Did you write any new necessary tests?

## What does this PR do?
Fixes # (issue).

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by edgarriba** [comment]
@tchaton initial proposal for a template tutorial file. Please, indicate what you miss or what else we could include.

**Comment by edgarriba** [comment]
@Borda can we disable `[E402] module level import not at top of file` ?

I guess there are some educational cases where we might want to include some imports in the top of a cell instead of the top of the file.

**Comment by Borda** [comment]
@edgarriba eventually you can flag it with `noqa` but fine to add this ignore :]

**Review by Borda — APPROVED** [review]

**Comment by justusschock** [comment]
How do we make sure, the template isn't deployed?

**Comment by edgarriba** [comment]
@justusschock good point - @Borda can we enable/disable that ?

**Comment by Borda** [comment]
> How do we make sure, the template isn't deployed?

you need to list each notebook you want to add in docs, so no problem :P
https://github.com/PyTorchLightning/pytorch-lightning/pull/8004#discussion_r653327498

**Review by ethanwharris — APPROVED** [review]

**Pull request merged**
