### PR TITLE
CI: check dead links in docs

### PR DESCRIPTION
**Pull request by Borda**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?

Fixes # (issue).

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]
nice tool! perfect as a ci job

**Review by ethanwharris — APPROVED** [review]
Neat!

**Comment by Borda** [comment]
I am fixing some dead links in the lectures and seems that one or more notebooks can't run again...
@phlippe mind have a look at what is happening there? :rabbit:

**Comment by phlippe** [comment]
Ah, the new PyTorch Geometric version broke our checkpoints by renaming some internal layers. I corrected the checkpoint, but we need to update the PyTorch Geometric. I will look into that tomorrow.

**Comment by Borda** [comment]
> I will look into that tomorrow.

do you prefer to update the notebook/checkpoint or just freeze the package version?

**Comment by phlippe** [comment]
> do you prefer to update the notebook/checkpoint or just freeze the package version?

I think in this case it made more sense to update the version in the meta file since we went from PyG 1.7 to 2.0. I do not expect more breaking changes any time soon.

**Pull request merged**
